Added cljs compile tasks

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -74,6 +74,24 @@ if [ "${PIPESTATUS[*]}" != "0 0" ]; then
   exit 1
 fi
 
+# Compile cljs
+echo "-----> Compiling development cljs"
+cd $BUILD_DIR
+lein run -m tasks.build-dev-js 2>&1
+if [ "${PIPESTATUS[*]}" != "0 0" ]; then
+  echo " !     Failed to compile development cljs"
+  exit 1
+fi
+echo "-----> Compiling advanced cljs"
+cd $BUILD_DIR
+lein run -m tasks.build-advancev-js 2>&1
+if [ "${PIPESTATUS[*]}" != "0 0" ]; then
+  echo " !     Failed to compile advanced cljs"
+  exit 1
+fi
+echo "-----> Compiling cljs completed"
+
+
 # repack cache with new assets
 rm -rf $CACHE_STORE_DIR
 mkdir -p $(dirname $CACHE_STORE_DIR)
